### PR TITLE
Added ckeditor to dashboard with save and preview button features

### PR DESCRIPTION
**Pull request by ildemartinez**
- Added the opensource ckeditor files in includes/editors/ckeditor
- Outside ckeditor directory added the new ckeditor features so it will be easy to update ckeditor with new releases without broke the emoncms ckeditor features
- Created two editor events for save and preview so the code is more elegant
- Save feature use the same ajax code
- Preview feature open a new window calling Vis/Dashboard/embed.php?apikey=******

Best regards from Spain

### CODE REVIEW

**Comment by TrystanLea** [comment]
Hello Ilde

Thanks a lot for the pull request! I really like the way the save and the preview button works, I tested it out with some text and it works great.

I am however having problems adding the widgets such a dial, if I enter the code in the source view

<div class="dial" feed="power" max="10000" units="W" scale="1"></div>


ckeditor seems to remove it completely after switching to the main view, do you get the same?

**Comment by ildemartinez** [comment]
Did you try to add the code in the html editor mode? First editor button (html source) and press save and then preview

It works fine for me

Best regards
ilde

**Comment by ildemartinez** [comment]
i updated the pull request with a modification. The same code from dashboard_view and embed is moved to common.js so the same code is only once and both first files are smaller so the code is easy to mantein and is only in one place.

**Comment by ildemartinez** [comment]
sorry... i closed it accidentally

**Comment by TrystanLea** [comment]
Yes I tried that, I get the same problem. I also get an issue that if I add a comma such as test'test, save it and reopen the page I get test&39;test, Happens in both firefox and chrome.

how strange..

**Comment by ildemartinez** [comment]
ok, i found the bug and fixed it..

in line 32 on dashboard_controller.php you should add # symbol because test'test is test& # 39 ; test in html :-)

**Comment by TrystanLea** [comment]
great that fixed the comma, my fault :) Im still getting the issue with the dial not displaying and Im pretty sure I have traced the issue to ckeditor stripping out <div class="dial" feed="power" max="10000" units="W" scale="1"></div> if it contains nothing between the open and close div. Is there a setting I wonder in ckeditor to stop it from doing this?

**Comment by TrystanLea** [comment]
If its only the dial element then it removes it completely, if there is a title as well, it puts a blank space in the dial element

The dial html is then no longer added on line 86-87 of common.js

**Comment by ildemartinez** [comment]
ok, i found it 

http://cksource.com/forums/viewtopic.php?f=11&t=16915&sid=027e13944d56171f979c934e0acf7c2a&start=10

i hope to have the fix soon

**Comment by TrystanLea** [comment]
great, no rush

**Comment by ildemartinez** [comment]
i think is fixed. I added some rules for the <div> tag so add nothing to that.

I found a issue with the dashboard and i dont know if is the correct way you want to work. If i write a < div class="dial" feed="power" max="500" scale="1" units="V"></div> then in the same page the <canvas... is added so if you press save all it is saved.

Do you want to work this way? or you want not save the <canvas... generated tags?... to find i fix for that

**Comment by ildemartinez** [comment]
i think is better this way... the < canvas tag is not visible in the editor, is only built in render time in the last pull request... did you agree with me? if not make me know

**Comment by ildemartinez** [comment]
i am sorry for making so many commits/pull... now in editor you can see the styles so visually editing is near ;-)

i sent you a screenshoot

**Comment by TrystanLea** [comment]
Wow, great that works! nice work

**Pull request merged**
