### PR TITLE
(#23) Dutch and Belgium Translation for new translation module

### PR DESCRIPTION
**Pull request by alco28**
Pull request for issue #23.
Made 2 translations. for country: The Netherlands (NL) and language Dutch.
and the second for country: Belgium, language Dutch.

### CODE REVIEW

**Comment by jsidrach** [comment]
Hi alco28, thanks for the translation.
The file should be name (language)_(COUNTRY), with 2 letters both.
Example:
Spanish from Spain (español de españa):
es_ES
English from England
en_EN
I hope it helps

**Comment by alco28** [comment]
Yes I did that. my files for this pull request are nl_NL (Dutch, from the Netherlands) and nl_BE for Dutch, for Belgium.
It's not common to rename that to du_NL or something like that. all software applications have nl for the translation. only when you make the metadata translation in the application it will be Dutch from country the Netherlands.

So I assume that my filename convention is OK at this pull.

**Comment by jsidrach** [comment]
Allright I was confused about the nl_ part (sorry about my poor knowledge).

**Comment by alco28** [comment]
That alright my friend :) that's why I explain it here :)

**Comment by TrystanLea** [comment]
Thanks a lot alco!

**Pull request merged**
