### PR TITLE
Processlist

### PR DESCRIPTION
**Pull request by mattwire**
Improve the process list screen:

```
Add functions to delete / move up / move down individual process entries.
Add dropdowns and auto-populate for feed and input.
```

See http://mjwconsult.co.uk/temp/process_screen.png for a screenshot of the changes.
Images are from openclipart.org:
http://openclipart.org/people/Anonymous/Anonymous_Arrow_Down_Blue.svg
http://openclipart.org/people/Anonymous/tasto_8_architetto_franc_01.svg

Cheers,
Matthew

### CODE REVIEW

**Comment by ildemartinez** [comment]
Great work Matt!!!

you could use bootstrap twitter icons as other icons in the project if you want to get the same look&feel ;-)

http://twitter.github.com/bootstrap/base-css.html#icons

All the best
ilde

**Comment by TrystanLea** [comment]
Hello Matt, thanks a lot for your work on this! The re-organisable process list and fixing of php errors is really great!  

Did you mean to delete the submenu/greymenu and fullwidth section in theme.php? 

I also seem to have now a conflict meaning the pull cannot be automatically merged, could you pull the latest changes and resubmit a pull request?

Thanks a lot

Trystan

**Comment by mattwire** [comment]
I deleted the menu sections and then forgot to put them back.  I'm working on merge conflicts now.

**Comment by TrystanLea** [comment]
cool, ok thanks a lot, let me know if I can help

**Comment by TrystanLea** [comment]
Thanks Matt for the pull request part 1, much appreciated, let me know if I can help with the above

**Comment by mattwire** [comment]
Hi Trystan,  Sorry for the delay, I've been rebuilding a fireplace...
I've now rebased this so there should be no merge conflicts.

I did not have time to change the icons as Ilde suggested, but happy for them to be changed to the twitter ones to match look and feel.  Or they could be changed later :)  Anyway this should be ready to merge.

**Comment by wiesson** [comment]
Please use the Bootstrap Icons, not your own - the boostrap icons look much nicer and altogether more coherent.

**Comment by ildemartinez** [comment]
The most important thing Is to merge all your great code and features.... I can change the icons after :-)

**Comment by TrystanLea** [comment]
Thanks a lot Matt

**Pull request merged**
