### PR TITLE
New dashboards features

### PR DESCRIPTION
**Pull request by ildemartinez**
Now there is a new menu item called dashboards (now i think dashboard menu item should be deleted :-)

There, a user can add new dashboards, preview, edit or delete it.

A new "id" param identifies the id dashboard used in embed.php and view pages.

You shoul call upgrade.php because the dashboard table now has a foreing key to the user table and two future use fields called name and description. These modifications are not in setup.php waiting for the best way to make upgrades in future (maybe a table with general information about version...).

### CODE REVIEW

**Comment by TrystanLea** [comment]
Thanks a lot Ilde, this is fantastic! Sorry for the delay in accepting the pull request, I've been on the road and I havent until now had the change to sit down and go through the request.

I wonder if the Dashboards page could be like a menu a series of tabs, when you click on a tab it loads up the edit view. Do you think it would also be possible to have the ckeditor minimized as default as it was originally and then when you click on edit the editor appears? 

What do you think?

**Comment by TrystanLea** [comment]
Also would it be possible to put the dashboard table upgrade details in the setup.php script in the root directory? the setup script is used to both do the initial database creation and updating tables if new fields are required etc. 

Thanks a lot for your hard work on this.

**Comment by ildemartinez** [comment]
Hi Trystan

dont worry about that... 

You are right, i think dashboards page can be improved in several ways. I used it to test database modifications and i am thinking in a better way to have multiples dashboards. I will try your proposal and how could it be with more than 10 or 20 dasboards.

I think it could be good to have "clone" dashboard feature so where to put that button in dashboards page (maybe a tool button on editor is the better way).
I will try to hide editor too so preview work could be faster.

Do you think setup.php could test and upgrade database if needed? ... i think same too but i didnt want to modify that file until it works fine and you accept modifications in database. I will try too ;-)

Best regards
ilde

**Comment by TrystanLea** [comment]
Great, yes a clone dashboard feature sounds good. I had an idea yesterday for maybe another feature along similar lines that may be good in the longer term: a template dashboard feature where we can select a pre-scripted template home energy monitoring dashboard or solar PV, this could make it really easy to get started with dashboards.

Yes I agree setup.php should be used for setup, test and upgrading.

All the best

Trystan

**Comment by ildemartinez** [comment]
The ckeditor enables the posibility to have code snipes or templates in an easy way. I will check that to get a template libraries ;-)

Regards
ilde

**Comment by TrystanLea** [comment]
Excellent!  ckeditor can do everything! :)

All the best

Trystan

**Pull request merged**
